version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mean_network

  backend:
    build:
      context: ./back-end-express-server
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - mean_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./front-end-angular
    ports:
      - "4200:80"
    networks:
      - mean_network
    depends_on:
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - mean_network

networks:
  mean_network:
    driver: bridge

volumes:
  mongodb_data:
